spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    initialize: true
    schema: classpath:/testData/schema.sql
    data: classpath:/testData/data.sql
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: kr.co.ps119.data.CustomPhysicalNamingStrategyImpl
  thymeleaf: 
    cache: false
  session:
    store-type: none
server.context-path: /myPractice