spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: kr.co.ps119.config.CustomPhysicalNamingStrategyImpl
  http:
    multipart:
      enabled: true
  devtools:
    restart:
      enabled: false

---

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # jdbc:h2:tcp://localhost/~/test
    username: admin
    password: thisisadmin
    initialize: true
    schema: classpath:/testData/schema.sql
    data: classpath:/testData/data.sql
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2/
      settings:
        web-allow-others: true
  thymeleaf: 
    cache: false
  session:
    store-type: none
server:
  context-path: /imcolla

#jdbc:h2:~/test

---

spring:
  profiles: prod
  
---
  
spring:
  profiles: test  